### ISSUE TITLE
is there a plan to port sparrow to swift?

### ISSUE THREAD

**Issue by yushli** [Gamua/Sparrow-Framework#37]
That would be great if there is such a plan. and what is the timeline if there is one? Thank you for your reply.

**Comment by colemancda** [comment]
@PrimaryFeather I am planning on porting Sparrow to Swift, with Android support. If I pursued this goal, would you be interested in supporting the project with your expertise?

**Comment by PrimaryFeather** [comment]
I'd love to see that, of course! And I'd do all I can to help — you can contact me anytime if you've got questions (daniel at gamua dot ...).

Maybe you should sync up with @racarone too, though! He's done a lot of the latest stuff in Sparrow. Finally, I'm currently working on a major architecture change in Starling, the port of Sparrow to ActionScript. Many of those concepts would fit very well with Sparrow, too! More information on the latter can be found [here](http://forum.starling-framework.org/topic/preview-starling-20).

**Comment by colemancda** [comment]
This is what I have been able to put together in a couple of days.

https://github.com/PureSwift/Swallow

	Coleman,

**Comment by racarone** [comment]
I had originally planned on porting Sparrow to Swift, and did actually make a working port, but in the end was so dissatisfied with how Swift performed I abandoned it. It was almost 7x slower! Mainly because Apple still hasn't optimized ARC in many areas. Something as simple as looping over an array of references types and calling a method can cause a retain and release on every iteration! Reference counting in my tests was accounting for 60-80 percent of CPU usage, which is completely ridiculous and negates any performance gained in areas where Swift can shine. This is the same issue Sparrow had when it was using ARC, but worse. ARC in Objective-C is actually better optimized than it is in Swift. Also, the only way to opt out of ARC in Swift is by using `unowned(unsafe)` variables or the `Unmanged<>` struct, which is verbose and ugly.

I also think the language is just a little too young and the architecture of Sparrow really leans on  Swift's weak points. For example, the EventDispatcher class relies heavily on Objective-C selectors and dynamic dispatch, which can be implemented in Swift, but then you lose any portability. It also feels hackish in Swift as it requires verbose checks and casting just so you can dynamically call a  method, as well as requiring the called method to be declared dynamic, @objc or by having its parent class inherit from NSObject. Closures on the other hand are the obvious option, but you can't compare them for equality. This means you can't remove event listeners without introducing some other mechanism, such as giving the closures a unique id or name. This is just one of many problems I encountered while porting Sparrow to Swift.

Sparrow and its cousin Starling both rely heavily on the dynamic features of Objective-C and Actionscript, while Swift in its current form is a very rigid language and just not built to handle these kinds of situations. Perhaps that will change in the future, but in its current state I just don't see any advantages in porting Sparrow to Swift.

I hate to be so discouraging on the matter, but I just want to give you some warning before you get too far into it. But if you do decide to keep moving forward with it, go for it and be sure to give us updates! Maybe you'll have some better success than me!

**Comment by colemancda** [comment]
Thanks for the advice @racarone. This is why am using Protocol Oriented Programming, and not OOB. For example, things like SPContext should be a class, but all the geometry types, should be structs. Thanks to protocols, and protocol extensions, structs with inheritance is possible. I already have a mental map of how to complete the port, and I am willing to put a of of time and effort nonetheless. As for event dispatcher, that is one feature where the mechanism just has to change, as it doesn't fit with Swift, and will end up being less performant (also no dynamic dispatch on Linux yet). Nonetheless, the actual rendering code can be successfully ported to Swift and be performant, but the code has to be heavily modified and not "translated" to Objective-C. What I would like, is to keep on working on this, do 90% of the hard work, and then contact @PrimaryFeather or @racarone, when issues arise, or to improve performance in the final stages.

Also for reference, right now in my port, `Context`, `Framebuffer` and `SPViewController` are the only classes. All the `SPPoolObject` objects are structs. This is not necessarily easy porting, but it can be done.

**Comment by colemancda** [comment]
Also, @racarone, any chance you have some of that ported Swift code lying around?

**Comment by racarone** [comment]
> Thanks for the advice @racarone. This is why am using Protocol Oriented Programming, and not OOB. For example, things like SPContext should be a class, but all the geometry types, should be structs. Thanks to protocols, and protocol extensions, structs with inheritance is possible.

Yes, the geometry types definitely make sense as structs. Daniel made those classes in Objective-C because it's provides a much cleaner API over using C structs and functions. While these classes and other low level classes, such as `VertexData`, are obviously better suited as structures or protocols in Swift, you would really have to deviate from Sparrow's API in order to implement protocol oriented programming for rest of the framework. 

While protocols do give structures a lot more flexibility, they do not give them true inheritance. Sparrow's rendering architecture is entirely based on inheritance, so without completely redesigning the framework to fit a another approach, it will be the main performance obstacle. Traversing the display tree every frame and calling any methods on `DisplayObject` and children classes is really where ARC nails you. Any time you touch a reference type in Swift, whether it's accessing a property or calling any method, you'll get a nice pre `swift_retain()` and post `swift_release()` to "hold" that object while you access it, a few more for any arguments passed as a reference, and finally the lovely cascading effect of that method internally calling other methods on classes. The ARC optimizer catches some of these, but not enough. This could be alleviated by implementing Starling 2.0's render caching, but without completely changing the rendering architecture or Apple actually improving their ARC optimizer, this problem will remain. 

Ideally in a more protocol based approach you'd probably throw out `DisplayObject` and children classes completely and use a `Node` based approach, similar to SpriteKit, with varied renderers that handle the leg work. Though in doing so you'd end up with something that bears very little resemblance to Sparrow. 

> As for event dispatcher, that is one feature where the mechanism just has to change, as it doesn't fit with Swift, and will end up being less performant (also no dynamic dispatch on Linux yet).

I agree, but it's a system that Sparrow and Starling rely heavily on. Implementing an event system in Swift, without making it cumbersome for the user is the challenge. 

> What I would like, is to keep on working on this, do 90% of the hard work, and then contact @PrimaryFeather or @racarone, when issues arise, or to improve performance in the final stages.

Well both of us would love to see what you come up with, just be aware that it's going to be a challenge to implement something that stays true to Sparrow and Starling while also achieving the performance you have in mind.

> Also, @racarone, any chance you have some of that ported Swift code lying around?

Here's a zip with a very incomplete port of Sparrow that does not work. It does contain some of the core classes such as the `DisplayObject` basic hierarchy and geometry types, but also contains a some convoluted implementations of `Context` and `EventDispatcher`. I wouldn't used this for anything but a reference for _some_ of the core classes.

https://www.dropbox.com/s/fszjb52pd6ubtxj/Sparrow-Swift.zip?dl=0

**Comment by colemancda** [comment]
@racarone Thank you very much. And yes, I am starting to see that now, I will try to create an API similar to Sparrow, but I do see that significant API changes are necessary. Thanks for the warning.

**Comment by PrimaryFeather** [comment]
Thanks a lot for this interesting comments, to both of you! 

Damn, I had hoped that Apple would have solved the ARC performance issues by now ... especially when there's no way around it in Swift. In Objective-C, manually updating your reference counters in performance-critical code (like a rendering framework) was a good-enough workaround, but when that's not possible ...?

Designing another event mechanism because the language is not good with dynamic calls? I could live with that, because it was probably a conscious decision of performance vs. flexibility. But having to use objects and method calls sparingly to have good performance? That's just not a good idea. :pensive:

On the other hand, Apple's doing a lot of work on the language, still. So let's just hope that stuff is a big item on their TODO list. :wink:

**Comment by racarone** [comment]
It's definitely getting better! In the interest of pursuing this further I made some changes to my previous code base and tested further. I'm have actually getting promising results! I might have skewed my perception of Swift a bit from previous attempts =P

Porting some of the new rendering code from Starling actually helps performance tremendously... Also, building Swift from the source and building from that compiler shows that there are further performance improvements to come, which is nice to look forward to. So all may not be lost, maybe there will be a Swift port sooner than I previously thought! =)

>Designing another event mechanism because the language is not good with dynamic calls? I could live with that, because it was probably a conscious decision of performance vs. flexibility. 

Definitely still need to design around this, hopefully we could come up with something that is simple and performant.

**Comment by PrimaryFeather** [comment]
Ah, great to hear that is *is* getting better, after all! Somehow, it looks as if Apple uses the developer community to get the language in a mature state, before they start to use it themselves in major projects. :wink: I recently [read](https://medium.com/@ryanolsonk/is-apple-using-swift-4a6c80f74599) that of all of Apple's iOS programs, only the *calculator* was written (almost) exclusively with Swift. I must say, I had expected them to have more faith in their new language!

But I'm sure they're getting there, and as much I loved Objective-C, it's good to have a modern successor on the way.

> Definitely still need to design around this, hopefully we could come up with something that is simple and performant.

Mhm, that definitely requires some thought! It's a similar problem in the Tween API, which was solved in SpriteKit with a quite elegant approach (even though it's not as straight-forward as the dynamic one that was possible in Sparrow thanks to Objective-C's dynamic nature).
